apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-60fb"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-60fb"
  template:
    metadata:
      labels:
        app: "aksdemo-60fb"
    spec:
      containers:
        - name: "aksdemo-60fb"
          image: "acrsekerdemo.azurecr.io/aksdemo"
          ports:
          - containerPort: 80