on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: fnacr101.azurecr.io
        username: ${{ secrets.acr_fnacr101_username }}
        password: ${{ secrets.acr_fnacr101_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t fnacr101.azurecr.io/akslab:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push fnacr101.azurecr.io/akslab:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akslab_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akslabb346 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akslabb346`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akslabb346
        container-registry-url: fnacr101.azurecr.io
        container-registry-username: ${{ secrets.acr_fnacr101_username }}
        container-registry-password: ${{ secrets.acr_fnacr101_password }}
        secret-name: akslabdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akslabb346
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          fnacr101.azurecr.io/akslab:${{ github.sha }}
        imagepullsecrets: |
          akslabdockerauth
